# Householder Matrices

In [2]:
import numpy as np

In [3]:
def myHouseholder1(a):
    
    a = a.reshape(-1,1) # First column of matrix A
    n = a.shape[0]      # Size of column vector a & matrix A
        
    # Determine * to minimize loss of significant digits
    # * = (norm of column vector a) x (opposite sign of element a[0])
    asterisk = np.linalg.norm(a) * (-np.sign(a[0]))
    
    v      = np.zeros(n)       # Create zero column vector v of size n
    v      = v.reshape(-1,1)
    v[0]   = 1                 # First element of column vector v be =1
    v      = a - asterisk*v    # v vector = difference vectors a and asterisk*v
    norm_v = np.linalg.norm(v) # Normalize vector v
    
    # Create column vector w
    w = v / norm_v 
    w = w.reshape(-1,1)
    
    return w

In [4]:
def myHouseholder2(A,w):
    # Calculate Household matrix B
    B = A - 2 * w @ w.T @ A 
    return B

In [5]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = A[:,0]
w = myHouseholder1(a)
B = myHouseholder2(A,w)

print("Matrix A:")
print(A)
print("\nColumn Vector w:")
print(w)
print("\nMatrix B:")
print(B)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Column Vector w:
[[0.74936356]
 [0.32852276]
 [0.57491482]]

Matrix B:
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 8.88178420e-16 -8.59655700e-02 -1.71931140e-01]
 [ 8.88178420e-16 -9.00439748e-01 -1.80087950e+00]]


In [6]:
A = np.array([[1,7/3],[-1,-1],[1,4],[1,0]])
a = A[:,0]
w = myHouseholder1(a)
B = myHouseholder2(A,w)

print("Matrix A:")
print(A)
print("\nColumn Vector w:")
print(w)
print("\nMatrix B:")
print(B)

Matrix A:
[[ 1.          2.33333333]
 [-1.         -1.        ]
 [ 1.          4.        ]
 [ 1.          0.        ]]

Column Vector w:
[[ 0.8660254 ]
 [-0.28867513]
 [ 0.28867513]
 [ 0.28867513]]

Matrix B:
[[-2.00000000e+00 -3.66666667e+00]
 [ 2.22044605e-16  1.00000000e+00]
 [-2.22044605e-16  2.00000000e+00]
 [-2.22044605e-16 -2.00000000e+00]]
