# Update and Solve the Least-Squares Problem

In [2]:
import numpy as np

In [3]:
def lspUpdating(R,c,a,beta):
    # Task 1: Find solution 'xold' for least-squares problem w/ R & c = Q^(T)*b 
    xold = np.linalg.solve(R,c)
    rold = np.linalg.norm(np.dot(R,xold) - c)

    # Find solution for min x in ||(A,a^T)*x - (b,beta)||
    # Solve new least-squares problem w/ (R Q_1^(T)*b , 0 Q_2^(T)*b , a^T beta)

    # Task 2: Use rotation matrices to solve new least-squares problem
    m, n = R.shape
    R = np.vstack([R,a])
    c = np.append(c,beta)

    for i in range(n):
        norm = np.sqrt(R[i,i]**2 + R[m,i]**2)
        cos_theta = R[i,i] / norm
        sin_theta = R[m,i] / norm
        
        rotation_matrix = np.eye(m+1)
        rotation_matrix[i,i] = cos_theta
        rotation_matrix[m,i] = -sin_theta
        rotation_matrix[i,m] = sin_theta
        rotation_matrix[m,m] = cos_theta

        R = np.dot(rotation_matrix,R)
        c = np.dot(rotation_matrix,c)

    # Task 3: Find solution 'x_new of the new least squares problem and its residual r_new
    xnew = np.linalg.solve(R[:n,:n], c[:n])
    rnew = np.linalg.norm(np.dot(R[:n,:n], xnew) - c[:n])

    return xold, rold, xnew, rnew

In [4]:
# EXAMPLE 1
R = np.array([[1, 2], [0, 1]])
c = np.array([1, 2])
a = np.array([1, 1])
beta = 4

print("Matrix R:")
print(R)
print("\nMatrix c:")
print(c)

xold, rold, xnew, rnew = lspUpdating(R, c, a, beta)

print("\nSolution xold:")
print(xold)
print("Residual rold:",rold)

print("\nSolution xnew:")
print(xnew)
print("Residual renew:",rnew)


Matrix R:
[[1 2]
 [0 1]]

Matrix c:
[1 2]

Solution xold:
[-3.  2.]
Residual rold: 0.0

Solution xnew:
[2.         0.33333333]
Residual renew: 0.0


In [5]:
# EXAMPLE 2
R    = np.array([[1,2,3],[0,4,5],[0,0,6]])
c    = np.array([1,2,1])
a    = np.array([1,1,1])
beta = 4

print("Matrix R:")
print(R)
print("\nMatrix c:")
print(c)

xold, rold, xnew, rnew = lspUpdating(R, c, a, beta)

print("\nSolution xold:")
print(xold)
print("Residual rold:",rold)

print("\nSolution xnew:")
print(xnew)
print("Residual rnew:",rnew)

Matrix R:
[[1 2 3]
 [0 4 5]
 [0 0 6]]

Matrix c:
[1 2 1]

Solution xold:
[-0.08333333  0.29166667  0.16666667]
Residual rold: 0.0

Solution xnew:
[1.89724311 0.22807018 0.13032581]
Residual rnew: 0.0
