# Solving Tridiagonal Systems

In [1]:
import numpy as np

In [2]:
def SolveTridiSystem(alpha, beta, gamma, b):
    n = len(alpha)
    
    for k in range(n-1):                
        gamma[k] = gamma[k] / alpha[k]  
        alpha[k+1] = alpha[k+1] - gamma[k] * beta[k]  

    # Forward Substitution for Ly = b
    y = np.zeros(n)
    y[0] = b[0]
    for k in range(1, n):
        y[k] = b[k] - gamma[k-1] * y[k-1]  

    # Back Substitution for Ux = y
    x = np.zeros(n)
    x[n-1] = y[n-1] / alpha[n-1]
    for k in range(n-2, -1, -1):
        x[k] = (y[k] - beta[k] * x[k+1]) / alpha[k]
    
    return x

In [3]:
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
b = np.array([1,2,3])

print("Matrix A:")
print(A)
print("\nVector b:")
print(b.reshape(-1,1))

n = len(A)
alpha    = np.zeros(n)
alpha[:] = np.diag(A)
beta     = np.zeros(n-1)
beta[:]  = np.diag(A, k=1)
gamma    = np.zeros(n-1)
gamma[:] = np.diag(A, k=-1)
    
x = SolveTridiSystem(alpha, beta, gamma, b)
print("\nSolution x:")
print(x.reshape(-1,1))

Matrix A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Vector b:
[[1]
 [2]
 [3]]

Solution x:
[[2.5]
 [4. ]
 [3.5]]


In [4]:
A = np.array([[4,2,0],[2,5,2],[0,2,5]])
b = np.array([4,6,10])

print("Matrix A:")
print(A)
print("\nVector b:")
print(b.reshape(-1,1))

n = len(A)
alpha    = np.zeros(n)
alpha[:] = np.diag(A)
beta     = np.zeros(n-1)
beta[:]  = np.diag(A, k=1)
gamma    = np.zeros(n-1)
gamma[:] = np.diag(A, k=-1)
    
x = SolveTridiSystem(alpha, beta, gamma, b)
print("\nSolution x:")
print(x.reshape(-1,1))

Matrix A:
[[4 2 0]
 [2 5 2]
 [0 2 5]]

Vector b:
[[ 4]
 [ 6]
 [10]]

Solution x:
[[1.]
 [0.]
 [2.]]
